### PR TITLE
Add packaging config

### PR DESCRIPTION
**Pull request by cthoyt**
This PR does the following:

1. Adds packaging configuration (`setup.py`/`setup.cfg`)
2. Adds testing configuration with `tox.ini`
3. Adds CI run based on `tox`

### CODE REVIEW

**Comment by kkaris** [comment]
You should rebase on the latest `indralab/master`.

**Comment by cthoyt** [comment]
failure of the tests on CI is due to `indra_db.exceptions.IndraDbException: No primary host available in defaults file.`. @kkaris can you set the appropriate value in the secrets for this repo? I don't have settings access

Also not sure what you mean rebasing off of indralab/master... I just started the branch from there and there haven't been commits since

**Comment by kkaris** [comment]
Like this:
image

**Comment by cthoyt** [comment]
@kkaris sorry about the confusion. I had indeed checked out from `indralab` but GitHub desktop betrayed me and re-oriented it to be against `johnbachman` since that's still the "real" upstream

**Pull request merged**
